export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_CLEAR = 'REGISTER_CLEAR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_CLEAR = 'LOGIN_CLEAR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_FAIL = 'GET_USER_DETAILS_FAIL';

export const ADD_A_PET = 'ADD_A_PET';
export const ADD_A_PET_FAIL = 'ADD_A_PET_FAIL';

export const GET_PETS = 'GET_PETS';
export const GET_PETS_FAIL = 'GET_PETS_FAIL';

export const GET_PET_BY_ID = 'GET_PET_BY_ID';
export const GET_PET_BY_ID_FAIL = 'GET_PET_BY_ID_FAIL';

export const EDIT_A_PET = 'EDIT_A_PET';
export const EDIT_A_PET_FAIL = 'EDIT_A_PET_FAIL';

export const DELETE_A_PET = 'DELETE_A_PET';
export const DELETE_A_PET_FAIL = 'DELETE_A_PET_FAIL';

export const FILTER_PETS = 'FILTER_PETS';
export const FILTER_PETS_FAIL = 'FILTER_PETS_FAIL';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const ADD_TO_WISHLIST_FAIL = 'ADD_TO_WISHLIST_FAIL';

export const GET_WISHLIST = 'GET_WISHLIST';
export const GET_WISHLIST_FAIL = 'GET_WISHLIST_FAIL';

export const REMOVE_PET_FROM_WISHLIST = 'REMOVE_PET_FROM_WISHLIST';
export const REMOVE_PET_FROM_WISHLIST_FAIL = 'REMOVE_PET_FROM_WISHLIST_FAIL';

export const ADOPT = 'ADOPT';
export const ADOPT_FAIL = 'ADOPT_FAIL';